<project name="MyInfArith" default="test" basedir=".">

    <!-- === Properties === -->
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="dist.dir" value="dist"/>
    <property name="test.dir" value="test/"/>
    <property name="main.class" value="MyInfArith"/>
    <property name="test.class" value="Tester"/>
    <property name="jar.name" value="MyInfArith.jar"/>
    <property name="testClean.file" value="test/transfer_valid_cases.py"/>

    <!-- === Clean === -->
    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <!-- === Init directories === -->
    <target name="init">
        <mkdir dir="${build.dir}"/>
        <mkdir dir="${dist.dir}"/>
        <mkdir dir="${test.dir}"/>
    </target>

    <!-- === Compile === -->
    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${build.dir}"/>
    </target>

    <target name="test_compile" depends="init">
        <javac srcdir="${test.dir}" destdir="${build.dir}"/>
    </target>

    <!-- === Test === -->
    <target name="test" depends="compile,test_compile">
        <java classname="${test.class}" classpath="${build.dir}" fork="true" failonerror="true"/>
    </target>

    <!-- === Clean Test Cases === -->
    <target name="test_clean">
       <exec executable="python3">
           <arg value="${testClean.file}"/>
       </exec>
    </target>

    <!-- === JAR === -->
    <target name="jar" depends="compile">
        <jar destfile="${dist.dir}/${jar.name}" basedir="${build.dir}">
            <manifest>
                <attribute name="Main-Class" value="${main.class}"/>
            </manifest>
        </jar>
    </target>
</project>
